# Generated by Django 2.1 on 2018-08-29 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fconn_app', '0002_auto_20180829_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='user',
            field=models.ManyToManyField(related_name='user_colleges', through='fconn_app.Checklist', to=settings.AUTH_USER_MODEL),
        ),
    ]
